name: Check

on:
  workflow_dispatch:
  # Run CI/CD jobs on pull request
  pull_request:
    paths:
      # only run jobs when source files are changed
      - src/**
      # or when this workflow file is changed
      - .github/workflows/check.yml
      # Add all monorepo dependency folders

jobs:
  check:
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      node: "24.x"
      pnpm: "10.33.0"
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm }}

      - name: Use Node.js ${{ env.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Ensure the files are linted before they are pushed
      - name: Lint
        run: |
          pnpm run lint
          $GITHUB_WORKSPACE/.github/scripts/assert_no_files_changed.sh

      # Run unit tests
      - name: Test
        run: pnpm run test

      # Ensure build not broken
      - name: Build
        run: pnpm run build
